version: "3"
services:
  bot:
    build: .
    environment:
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
  db:
    image: sqlite:latest
    volumes:
      - db_data:/data

volumes:
  db_data: